name: Deployning to Production on k8s cluster

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2

      - name: Docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}    
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker-build-web-image-push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/docker/Dockerfile.web
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web:${{ github.sha }}    

      - name: Docker-build-backend-image-push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/docker/Dockerfile.be
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}    

      